### ISSUE TITLE
Edit styling of the profile page

### ISSUE THREAD

**Issue by anasommer** [NoroffFEU/agency.noroff.dev#261]
The style of the user's profile page are a little bit different from the one in Figma design. [https://www.figma.com/file/hWJsAz3LDOfLmoYag2zvPS/dekstop-vesrion-for-editing?type=design&node-id=0%3A1&mode=design&t=DP59vysf4TXqFlJD-1](Figma)

- [x] Change the background of the Skills section 
- [x] Change the background of the About me section

**Comment by corrado1982** [comment]
Changed the background of Skills and About Me Sections with "theme-new-grey".
Made fonts more similar to the figma draw and hardcoded and styled the "skills" <li>  inside a <ul> added class="d-flex flex-wrap".
I didn't remove the shadows because I was not sure about it... and I could not adjust the style of "EDIT PROFILE" button because I could not see it from my branch, (maybe because when I cloned the repo the button was not created yet?!).
Should we create another task to adjust the button?
And what about the shadow? It should stay there or remove it as in the draw?
