### ISSUE TITLE
Button contrast error

### ISSUE THREAD

**Issue by saibia8** [NoroffFEU/agency.noroff.dev#277]
I checked the page using the Wave Evaluation tool, and it identified a contrast error on the buttons. To resolve this, we could change the text color to black.
![Contrast-error](https://github.com/NoroffFEU/agency.noroff.dev/assets/104776669/654ec408-4247-4718-ab41-d2ec43f36ed3)

**Comment by Bjonne696** [comment]
Changed text collor from light to black in elements with class btn-theme-primary.
This was done in these paths:

index.html
pages→listings→ index.html
src→js→templates→listings→renderListings.js
pages→auth→registrer→company→index.html
pages→auth→registrer→applicant→index.html 
pages→auth→login→index.html

Could not find any other instances where this problem was replicated.
