### ISSUE TITLE
modal

### ISSUE THREAD

**Issue by jkjode** [NoroffFEU/agency.noroff.dev#317]
Modals from Figma are not working in the html files (e.g. listings/listing/create)

**Comment by Spekkhogger** [comment]
Looking at the Figma a lot of the files in pages are ment to be modals.
List: 
* Listings/create
* Listings/edit 
* TBD/apply
* Login
* Register 

Reviewing if it's feasible to make this change for some of the pages now...

**Comment by Spekkhogger** [comment]
To clarify: The modals are already created and designed as they are in the Figma Hi-fi file. However, they are not placed on the correct pages, as some of the pages have not been made yet/some are made by JS with a mockAPI. 

Conclusion: Changing all mentioned pages to modals would require more time. It could possibly disrupt the work and progress of the other teams. It will require moving pages around and deleting some pages. Because of these reasons I won't move ahead with moving the modals into the correct files at this time. 

Instead, I'll write comments for future developers in the code that will hopefully make this process easier and faster when it's time to do it.
