### ISSUE TITLE
API request for Edit profile

### ISSUE THREAD

**Issue by anasommer** [NoroffFEU/agency.noroff.dev#331]
The Edit profile functionality doesn't work, nothing changes when I try to update my profile information.

- Investigate the page
- check if there is some javascript connected
-  is it connected to the API
-  is it sending a PUT request to the API?

**Comment by corrado1982** [comment]
I think something is already working here:
src\js\listeners\profile\handleEditForm.js

I had just a look on it but I didn t investigate if it works also with the API

**Comment by elli95** [comment]
It doesn't work yet.
Currently getting a 404 error "User with id doesn't exist."
Also in handleEditForm.js, line 22, there is a typo.
it says "studentForm.addEventListener" but it should say "companyForm.addEventListener".
If I understand this correctly at least.

**Comment by runeunhjem** [comment]
Assigning this to Elise

**Comment by elli95** [comment]
Typo at handleEditForm.js, line 22 is fixed. 
404 error "User with id doesn't exist." is fixed. 
Now I get 403 error "Email is already in use." 
Will check the api documentation, and work from there.

**Comment by elli95** [comment]
Editing works, just have to have the same email that belongs to the user.

**Comment by elli95** [comment]
I can now edit the picture, title (not otherwise shown on the profile page), skills and description.
At the moment I have found some errors and points that should be changed.

Editing email does not work. 
I am not sure if you are suposed to be able to edit it, but I just gets an error 403 "Email is already in use." when I try.

Editing of names is approved, but no changes take place.
The input field in the code contains both first and last name and is named fullName. Whereas in the api documentation this information is divided into first name and last name.
I think a change or new function needs to be added for this information to be properly communicated.

The skill field is not correctly displayed with new info, placeholder texts remain while new date is displayed as one long word.

Furthermore, I also have problems creating a company user, and thus cannot test the profile page for them right now. From what I see in the codes, I think it has the same problems as applicant profiles.

**Comment by elli95** [comment]
Added a new input field for both first and last name, you can now edit your name.

**Comment by elli95** [comment]
Pull request [#554](https://github.com/NoroffFEU/agency.noroff.dev/pull/554)
