### ISSUE TITLE
Use that create html function to change the render function to use create element instead of a string and so on

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#494]

**Comment by Tokle89** [comment]
I have: 
 Rewrote the function to use createElements, instead of forcing a string into the DOM.
The function now also uses the API to get the data, instead of using a Lorem Ipsum, but still uses the same structure as before.
The function also uses the createElements function to create the elements, instead of creating them manually.
The Api call still comes from a dummy API, but the function is ready to be used with the actual API.
Deleted the searchListings import as it was never used

But now that the cards have different text and img,  the scss needs to be updated as the cards have different height and so on

**Comment by runeunhjem** [comment]
Pull request https://github.com/NoroffFEU/agency.noroff.dev/pull/545
