### ISSUE TITLE
Create functional listing page

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#756]
Creating code for the listing, changing the api function to fetch from the noroff api, and rendering the listing

Figma:
https://www.figma.com/file/JBKuBV7FH9yrmcq4MUhKid/Hi-fi-wireframes?type=design&node-id=135%3A2329&mode=design&t=nfyMWd8SqhnbZQhM-1

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/106075565/72adb9dd-ba34-4c49-834f-1d1506a096fc)

**Comment by Tokle89** [comment]
Thanks! Will start on this task on monday bossman ;)

**Comment by Tokle89** [comment]
Have fixed an routing error, so that the router function works on the details page.
have also fixed the view singe listing function so the api works on fetching a signle listing

but i have discovered to different files for rendering a listing, that are called but not working, and i am struggeling to make sense of them.
dont know if i should create my own, or try to get the older functions to work?
also if i create my own rendering function, should i delete thoose files?
can you check this for me @runeunhjem ?

the files in question are:   "singleApplicationTemplate.js"  and "singleListingTemplate"
Both are called in the mess that i am workin on, but non of thoose are working due to small errors.
So i would like to get clarity in this before i start fixing the rendering of the listing

the singeApplicationtemplate function are targeting my the container id on the html file but never called-
the singlelistingtemplate are called in the viewsignelisting funciton on the "viewSingleListing.js" but does not work.

hope this makes sense

**Comment by runeunhjem** [comment]
If you feel comfortable creating your own well written function for rendering, go for it. Just remember there should be 2 different versions. One for applicants and one that shows edit/delete if role in localstorage is Client"

Do not delete the old ones... I want to check these more therally tomorrow

**Comment by Tokle89** [comment]
Great! I prefer to create my own function for this, especially this the old ones are not working.

Do u know if i can create my own client account, so i can test the two different versions?

**Comment by Tokle89** [comment]
@runeunhjem 
i have now finished the rendering,  but the page needs  btn functionality for the apply/edit and delete

i made my own local storage function, and adjusted my if statement so the code for changing the listing accoridng to the user works.
but i will wait to create a pullrequest til tomorrow after Ole have looked over the original local storage function that is causing problems.

link to repo if u or @Olekrr  want to have a look

https://github.com/NoroffFEU/agency.noroff.dev/tree/%23756-create-functional-listing-page

**Comment by runeunhjem** [comment]
Great. Will also have a lok at it tomorrow

**Comment by Tokle89** [comment]
have finished the ticket, and created a pull request.
link to pr: https://github.com/NoroffFEU/agency.noroff.dev/pull/891

the site still needs som small scss styling,  and the apply for job, edit and delete btn has no form functionality. i talked to rune earlier and we agreed that it should be created new ticket for this

**Comment by Tokle89** [comment]
Have fixed the link on A tags for listing cards on the listings page

from: `const a = createElement(
    'a',
    ['bg-theme-primary', 'text-theme-black', 'px-3', 'text-decoration-none'],
    null,
    'View',
    '../../..//pages/listings/listing/index.html'
  );`

to: ` const a = createElement(
    'a',
    ['bg-theme-primary', 'text-theme-black', 'px-3', 'text-decoration-none'],
    null,
    'View',
    '/pages/listings/listing/index.html?id=' + id ,
  );`
